version: '3.4'

services:
  db:
    restart: always
    image: postgres:latest
    container_name: xemacars_db
    networks:
      - xemacars
    environment:
      POSTGRES_DB: xemacarsdb
      POSTGRES_USER: xemacars
      POSTGRES_PASSWORD: xemacars
  web:
    restart: always
    container_name: xemacars_web
    image: xemacars_web:latest
    build: .
    command: /bin/bash -c "python manage.py migrate && gunicorn -w 5 XemaCars_ECommerce.wsgi --timeout=500 -b 0.0.0.0:8000"
    expose:
      - "8000"
    networks:
      - xemacars
    depends_on:
      - db

networks:
  xemacars:
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 10.5.0.0/16
